# Generated by Django 3.0.6 on 2020-05-08 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcomment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_adcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcomment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_ads_adcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcomment',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_ads_adcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_ad_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_ads_ad_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_ads_ad_comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
