# Generated by Django 3.0.8 on 2020-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200920_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='postal_code',
            field=models.CharField(default='L3R8K5', max_length=6),
            preserve_default=False,
        ),
    ]
