# Generated by Django 3.0.6 on 2020-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Electronics'), (1, 'Books'), (2, 'Food'), (3, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='postal_code',
            field=models.CharField(default='A1B2C3', max_length=6),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ad',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waterloo'), (1, 'Toronto'), (2, 'Brampton'), (3, 'Ottawa')], default=0),
        ),
    ]
