# Generated by Django 3.1.1 on 2020-10-16 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_ad_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_ads_ad_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ad',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_ads_ad_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ad',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_ads_ad_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
