# Generated by Django 3.1.1 on 2020-10-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_adcomment_saved_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='saved_posts',
            new_name='saved_users',
        ),
        migrations.RenameField(
            model_name='adcomment',
            old_name='saved_posts',
            new_name='saved_users',
        ),
    ]
