# Generated by Django 3.1.1 on 2020-09-18 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20200508_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcomment',
            old_name='comment_body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='division',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street_address',
        ),
        migrations.AddField(
            model_name='event',
            name='comments_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='likes_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='price_scale',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$'), (5, '$$$$$')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='likes_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_event_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
