# Generated by Django 3.0.8 on 2020-09-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200920_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
