# Generated by Django 3.0.6 on 2020-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='123 Goose st, Waterloo, ON', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_scale',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$'), (5, '$$$$$')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waterloo'), (1, 'Toronto'), (2, 'Brampton'), (3, 'Ottawa')], default=0),
        ),
    ]
