# Generated by Django 3.1.1 on 2020-10-16 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_events_event_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_events_event_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_events_event_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
