# Generated by Django 3.1.1 on 2020-10-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201011_2130'),
        ('events', '0008_auto_20201015_2324'),
    ]

    operations = [
    ]
