# Generated by Django 3.1.1 on 2020-10-16 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200920_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_posts_post_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts_post_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts_post_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
