# Generated by Django 3.1.1 on 2020-10-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201015_2324'),
        ('posts', '0005_auto_20201011_2130'),
    ]

    operations = [
    ]
