export const mockUser = {
  id: 1,
  email: 'd22baker@uwaterloo.ca',
  last_login: '2020-10-26T20:39:52.376871Z',
  first_name: 'Deandre',
  last_name: 'Baker',
  preferred_name: 'Dre',
  pronouns: 4,
  bio: 'Listen fall job realize position. Spring baby authority list democratic evidence wide now.',
  birthday: '1969-03-30',
  current_term: 8,
  enrolled_program: 1,
  phone_number: '1794410497617',
  profile_photo:
    'http://dev.umigrate.ca/media/images/user_profile_photos/download_1.jpg',
  background_photo:
    'http://dev.umigrate.ca/media/images/user_background_photos/images_1.jpg',
  community: 1,
  datetime_created: '2020-10-21T02:42:24.051746Z',
  notification_privacy: 0,
  allow_location: false,
  currency: 0,
  language: 0,
  dark_theme: false,
  connected_users: [],
  blocked_users: [43, 50, 65, 91, 99],
};

export const mockPost = {
  id: 120,
  creator: {
    id: 46,
    preferred_name: 'Lisa Dalton',
    profile_photo: null,
    background_photo: null,
    is_connected: false,
    is_blocked: false,
  },
  is_liked: false,
  is_saved: false,
  likes: 1,
  comments: 1,
  most_liked_comment: {
    id: 716,
    creator: {
      id: 63,
      preferred_name: 'Christopher Jones',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    is_liked: false,
    is_saved: false,
    likes: 0,
    replies: 12,
    most_liked_reply: {
      id: 4396,
      creator: {
        id: 44,
        preferred_name: 'Patrick Henry',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
      is_liked: false,
      is_saved: false,
      likes: 3,
      tagged_users: [
        {
          id: 6,
          preferred_name: 'Lori Rodriguez',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
        {
          id: 44,
          preferred_name: 'Patrick Henry',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
        {
          id: 60,
          preferred_name: 'Tony Garcia',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
      ],
      content:
        'Series painting future ask figure reach. Various still minute three audience. Easy medical even whether decade cup agree. Hit piece rate yeah cut kid professional.',
      community: 2,
      datetime_created: '2020-10-21T02:45:59.534513Z',
      comment: 716,
    },
    tagged_users: [],
    content:
      'Ground indicate girl class bag simply allow travel. Same hot address become their fly truth.',
    community: 2,
    datetime_created: '2020-10-21T02:45:59.342643Z',
    object_id: 120,
    content_type: 22,
  },
  tagged_users: [
    {
      id: 29,
      preferred_name: 'Alyssa Swanson',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
  ],
  photos: [],
  title: 'Somebody program time deal. Trip win its stock listen or list.',
  content:
    'Listen street score this skin ability task. Police exactly cell different through environmental. Performance car state.',
  community: 2,
  datetime_created: '2020-10-21T02:45:58.456297Z',
};

export const mockEvent = {
  id: 119,
  creator: {
    id: 29,
    preferred_name: 'Alyssa Swanson',
    profile_photo: null,
    background_photo: null,
    is_connected: false,
    is_blocked: false,
  },
  is_liked: false,
  is_saved: false,
  likes: 1,
  comments: 3,
  most_liked_comment: {
    id: 710,
    creator: {
      id: 116,
      preferred_name: 'Candace Daniels',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    is_liked: false,
    is_saved: false,
    likes: 3,
    replies: 3,
    most_liked_reply: {
      id: 4344,
      creator: {
        id: 22,
        preferred_name: 'Terry Larsen',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
      is_liked: false,
      is_saved: false,
      likes: 3,
      tagged_users: [
        {
          id: 52,
          preferred_name: 'Stephanie Sanchez',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
        {
          id: 67,
          preferred_name: 'Brandon Gross',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
        {
          id: 111,
          preferred_name: 'Barry Smith',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
      ],
      content:
        'Popular who worry onto. Free guy effort. Front call improve protect marriage class still all. Whether onto lay camera life use.',
      community: 1,
      datetime_created: '2020-10-21T02:45:57.762481Z',
      comment: 710,
    },
    tagged_users: [
      {
        id: 8,
        preferred_name: 'Katherine Bowers',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
    ],
    content:
      'Compare model hospital business blue huge into. Official shoulder official along media difficult phone factor. Must training ever I feel cause author major.',
    community: 0,
    datetime_created: '2020-10-21T02:45:57.694775Z',
    object_id: 119,
    content_type: 14,
  },
};

export const mockAd = {
  id: 119,
  creator: {
    id: 119,
    preferred_name: 'Justin White',
    profile_photo: null,
    background_photo: null,
    is_connected: false,
    is_blocked: false,
  },
  is_liked: false,
  is_saved: false,
  likes: 3,
  comments: 1,
  most_liked_comment: {
    id: 712,
    creator: {
      id: 113,
      preferred_name: 'Randy Peterson',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    is_liked: false,
    is_saved: false,
    likes: 1,
    replies: 3,
    most_liked_reply: {
      id: 4348,
      creator: {
        id: 90,
        preferred_name: 'Lauren Myers',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
      is_liked: false,
      is_saved: false,
      likes: 3,
      tagged_users: [],
      content:
        'Red according east particular debate song dog speech. He past economic radio.',
      community: 2,
      datetime_created: '2020-10-21T02:45:57.913997Z',
      comment: 712,
    },
    tagged_users: [
      {
        id: 9,
        preferred_name: 'Stephanie Jennings',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
      {
        id: 17,
        preferred_name: 'Ryan Smith',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
      {
        id: 108,
        preferred_name: 'Denise Casey',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
    ],
    content:
      'Maintain total exactly theory help head produce. Middle less score fight yet. Short television station cause.',
    community: 2,
    datetime_created: '2020-10-21T02:45:57.888778Z',
    object_id: 119,
    content_type: 13,
  },
  tagged_users: [
    {
      id: 64,
      preferred_name: 'Dakota Hart',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    {
      id: 105,
      preferred_name: 'Ashley Higgins',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
  ],
  photos: [],
  title: 'Especially purpose learn for social vote.',
  content:
    'Conference however outside draw. Western benefit suddenly avoid another live.',
  community: 2,
  datetime_created: '2020-10-21T02:45:57.088566Z',
  category: 1,
  price: '-540236.49',
  postal_code: 'C6K0S6',
};

export const mockListing = {
  id: 120,
  creator: {
    id: 106,
    preferred_name: 'Sean Kirk',
    profile_photo: null,
    background_photo: null,
    is_connected: false,
    is_blocked: false,
  },
  is_liked: false,
  is_saved: false,
  likes: 2,
  comments: 2,
  most_liked_comment: {
    id: 714,
    creator: {
      id: 82,
      preferred_name: 'Jeffrey Smith',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    is_liked: false,
    is_saved: false,
    likes: 1,
    replies: 12,
    most_liked_reply: {
      id: 4373,
      creator: {
        id: 80,
        preferred_name: 'Kenneth Martinez',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
      is_liked: false,
      is_saved: false,
      likes: 3,
      tagged_users: [
        {
          id: 14,
          preferred_name: 'David Morgan',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
        {
          id: 27,
          preferred_name: 'Annette Mason',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
        {
          id: 53,
          preferred_name: 'Jennifer Carey',
          profile_photo: null,
          background_photo: null,
          is_connected: false,
          is_blocked: false,
        },
      ],
      content:
        'Risk cold play least garden line. Room professional play animal history condition participant thing. Sport billion price become agreement discussion safe foot. Growth growth add spring.',
      community: 1,
      datetime_created: '2020-10-21T02:45:59.022604Z',
      comment: 714,
    },
    tagged_users: [],
    content: 'It amount father miss issue off.',
    community: 1,
    datetime_created: '2020-10-21T02:45:58.770986Z',
    object_id: 120,
    content_type: 15,
  },
  tagged_users: [
    {
      id: 25,
      preferred_name: 'Brian Hernandez',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    {
      id: 52,
      preferred_name: 'Stephanie Sanchez',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    {
      id: 108,
      preferred_name: 'Denise Casey',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
  ],
  photos: [],
  title:
    'Article two without foot condition. Always couple machine clearly man ready.',
  content:
    'Policy represent rock appear sense yet. Father age hard without laugh. Parent so always community can those police.',
  community: 2,
  datetime_created: '2020-10-21T02:45:58.051749Z',
  category: 0,
  price: '-79413.00',
  season: 0,
  year: 2001,
  location: '074 Elizabeth Curve\nRandallmouth, AK 05782',
};

export const mockComment = {
  id: 713,
  creator: {
    id: 25,
    preferred_name: 'Brian Hernandez',
    profile_photo: null,
    background_photo: null,
    is_connected: false,
    is_blocked: false,
  },
  is_liked: false,
  is_saved: false,
  likes: 1,
  replies: 12,
  most_liked_reply: {
    id: 4362,
    creator: {
      id: 111,
      preferred_name: 'Barry Smith',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    is_liked: false,
    is_saved: false,
    likes: 3,
    tagged_users: [
      {
        id: 17,
        preferred_name: 'Ryan Smith',
        profile_photo: null,
        background_photo: null,
        is_connected: false,
        is_blocked: false,
      },
    ],
    content:
      'Right open guy point discuss deep mind. School contain turn walk because language. Best that guess take loss simply. Model teach knowledge remain.',
    community: 0,
    datetime_created: '2020-10-21T02:45:58.750845Z',
    comment: 713,
  },
  tagged_users: [
    {
      id: 17,
      preferred_name: 'Ryan Smith',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    {
      id: 66,
      preferred_name: 'Timothy Mayo',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    {
      id: 80,
      preferred_name: 'Kenneth Martinez',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
  ],
  content:
    'Stop keep education set. Economy positive Republican so next. Then eight audience.',
  community: 1,
  datetime_created: '2020-10-21T02:45:58.478603Z',
  object_id: 120,
  content_type: 19,
};

export const mockReply = {
  id: 4398,
  creator: {
    id: 55,
    preferred_name: 'Christopher Richardson',
    profile_photo: null,
    background_photo: null,
    is_connected: false,
    is_blocked: false,
  },
  is_liked: false,
  is_saved: false,
  likes: 1,
  tagged_users: [
    {
      id: 75,
      preferred_name: 'Craig Pham',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
    {
      id: 87,
      preferred_name: 'Tami Daniels',
      profile_photo: null,
      background_photo: null,
      is_connected: false,
      is_blocked: false,
    },
  ],
  content:
    'Let stop property hit boy fear when. Avoid have bank maintain myself population. Painting government project each whether recently including inside.',
  community: 0,
  datetime_created: '2020-10-21T02:45:59.586510Z',
  comment: 716,
};
