export const routes = {
  login: 'Login',
  registration: 'Registration',
  passwordReset: 'PasswordReset',
  tabs: 'Tabs',
  messaging: 'Messaging',
  notifications: 'Notifications',
  comments: 'SharedItem',
  community: 'Community',
  market: 'Market',
  createItem: 'Create',
  housing: 'Housing',
  menu: 'Menu',
  menuHome: 'MenuHome',
  profile: 'Profile',
  editProfile: 'EditProfile',
  savedHome: 'SavedHome',
  posts: 'Posts',
  events: 'Events',
  ads: 'Ads',
  listings: 'listings',
  calendar: 'Calendar',
  settings: 'Settings',
};
