# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(MajorVersion).$(MinorVersion)

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - infrastructure/*
    exclude:
      - infrastructure/deployment/azure-pipelines.yml

pr:      
  branches:
    include:
    - main
  paths:
    include:
      - infrastructure/*
    exclude:
      - infrastructure/deployment/azure-pipelines.yml

variables:
- name: MajorVersion
  value: 0.0
- name: MinorVersion
  value: $[counter(format('{0}-{1}', variables['Build.SourceBranch'], variables['MajorVersion']), 0)]
- name: IsMain
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: IsPr
  value: $[contains(variables['Build.SourceBranch'], 'refs/pull/')]
- name: IsBranch
  value: $[and(eq(variables['IsPr'], 'False'), eq(variables['IsMain'], 'False'))]

jobs:
- job: 'Job'
  displayName: 'Build & Publish'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Infrastructure Source Files'
    inputs:
      SourceFolder: 'infrastructure/src'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
  - task: CopyFiles@2
    displayName: 'Copy Infrastructure Deployment Scripts'
    inputs:
      SourceFolder: 'infrastructure/deployment/scripts'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/scripts'

  - task: CopyFiles@2
    displayName: 'Copy Infrastructure Test Files'
    inputs:
      SourceFolder: 'infrastructure/tests'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
