# Generated by Django 3.1.3 on 2020-11-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=1000)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-datetime_created"],
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=1000)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime_created"],
            },
        ),
    ]
