# Generated by Django 3.0.6 on 2020-05-08 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/job_photos')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('job_type', models.PositiveSmallIntegerField(choices=[(0, 'Full-time'), (1, 'Internship')])),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('division', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
