# Generated by Django 3.1.1 on 2020-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
