# Generated by Django 3.1.1 on 2020-09-18 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='division',
        ),
        migrations.AddField(
            model_name='job',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_job_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
