# Generated by Django 3.1.1 on 2020-10-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200917_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='photo',
            new_name='background_photo',
        ),
    ]
