# Generated by Django 3.0.6 on 2020-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20201008_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(default='Waterloo', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='uMigrate', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full-time'), (1, 'Internship')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(default='Software Engineer Associate', max_length=100),
        ),
    ]
