# Generated by Django 3.2.3 on 2021-05-31 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("messaging", "0002_auto_20201128_2031"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
