# Generated by Django 3.2.4 on 2021-06-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_auto_20210531_0258 2"),
        ("messaging", "0004_alter_message_content_type"),
        ("messaging", "0004_alter_message_content_type 2"),
    ]

    operations = []
