# Generated by Django 3.0.6 on 2020-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20201008_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='privacy_level',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Direct Messaging')], default=0),
        ),
    ]
