# Generated by Django 3.0.6 on 2020-10-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20201011_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='photo',
        ),
        migrations.AddField(
            model_name='message',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='images/message_background_photos'),
        ),
        migrations.AddField(
            model_name='message',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='images/message_profile_photos'),
        ),
    ]
