# Generated by Django 3.1.3 on 2020-11-29 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="polls.option",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_polls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_polls", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="saved_users",
            field=models.ManyToManyField(
                blank=True, related_name="saved_polls", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_polls", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_options",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="polls.poll",
            ),
        ),
    ]
