# Generated by Django 3.2 on 2021-05-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_auto_20201128_2031"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
