# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(MajorVersion).$(MinorVersion)

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - api/*
    exclude:
      - api/deployment/azure-pipelines.yml

pr:      
  branches:
    include:
    - master
  paths:
    include:
      - api/*
    exclude:
      - api/deployment/azure-pipelines.yml

variables:
- name: MajorVersion
  value: 0.0
- name: MinorVersion
  value: $[counter(format('{0}-{1}', variables['Build.SourceBranch'], variables['MajorVersion']), 0)]
- name: IsMaster
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
- name: IsPr
  value: $[contains(variables['Build.SourceBranch'], 'refs/pull/')]
- name: IsBranch
  value: $[and(eq(variables['IsPr'], 'False'), eq(variables['IsMaster'], 'False'))]

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
 
  #- script: pip install Django djangorestframework django-filter Pillow psycopg2 bcrypt django-cors-headers channels channels-redis sendgrid
    #displayName: 'Install requirements'
  
  - script: pip install -r api/src/requirements.txt
    displayName: 'Install requirements'
      
  - task: PythonScript@0
    inputs:
     scriptPath: 'api/src/manage.py'
     arguments: 'test'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'api/src'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
