# Generated by Django 3.1.3 on 2020-11-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(blank=True, max_length=1000)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Waterloo"),
                            (1, "Toronto"),
                            (2, "Brampton"),
                            (3, "Ottawa"),
                        ]
                    ),
                ),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Condominium"),
                            (1, "Townhouse"),
                            (2, "Apartment"),
                        ],
                        default=0,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "season",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Winter"), (1, "Spring"), (2, "Fall")], default=0
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2020)),
                ("quantity", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoommatePost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(blank=True, max_length=1000)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Waterloo"),
                            (1, "Toronto"),
                            (2, "Brampton"),
                            (3, "Ottawa"),
                        ]
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
    ]
