# Generated by Django 3.1.1 on 2020-10-19 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcomment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_listingcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_listings_listingcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='saved_users',
            field=models.ManyToManyField(blank=True, related_name='saved_listings_listingcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_listings_listingcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_listing_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_listings_listing_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='saved_users',
            field=models.ManyToManyField(blank=True, related_name='saved_listings_listing_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_listings_listing_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
