# Generated by Django 3.1.1 on 2020-09-18 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingcomment',
            old_name='comment_body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='division',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='features',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='term',
        ),
        migrations.AddField(
            model_name='listing',
            name='comments_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='likes_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Fall')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='likes_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_listing_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
