# Generated by Django 3.0.6 on 2020-09-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200917_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='listingcomment',
            name='likes_count',
        ),
    ]
