# Generated by Django 3.0.6 on 2020-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Condominium'), (1, 'Townhouse'), (2, 'Apartment')], default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(default='123 Goose st, Waterloo, ON', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waterloo'), (1, 'Toronto'), (2, 'Brampton'), (3, 'Ottawa')], default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Fall')], default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
