# Generated by Django 3.1.1 on 2020-10-16 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0005_auto_20201015_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcomment',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_listings_listingcomment_comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
