# Generated by Django 3.1.1 on 2020-10-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20201015_2324'),
        ('listings', '0006_auto_20201012_1907'),
    ]

    operations = [
    ]
