# Generated by Django 3.1.1 on 2020-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrolled_program',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Engineering'), (2, 'Arts'), (3, 'Mathematics'), (4, 'Science'), (5, 'Applied Health Sciences'), (6, 'Environment'), (7, 'Theology'), (8, 'Graduate Studies'), (9, 'Independent Studies'), (10, 'Interdisciplinary'), (11, 'Conrad Grebel'), (12, 'Renison'), (13, 'St. Pauls'), (14, 'St. Jeromes')], default=0),
        ),
    ]
