# Generated by Django 3.1.1 on 2020-09-18 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200910_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followed_users',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
        migrations.AddField(
            model_name='customuser',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='_customuser_connected_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pronouns',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'None'), (1, 'He/Him'), (2, 'She/Her'), (3, 'They/Them'), (4, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(max_length=30),
        ),
    ]
