# Generated by Django 3.2.4 on 2021-07-04 06:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210703_1814"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notification_preferences",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("SharedItem", "SharedItem"),
                    ("Message", "Message"),
                    ("Comment", "Comment"),
                    ("Tag", "Tag"),
                    ("Connection", "Connection"),
                ],
                default="SharedItem,Message,Comment,Tag,Connection",
                max_length=41,
                null=True,
            ),
        ),
    ]
