# Generated by Django 3.1.1 on 2020-10-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200917_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='images/user_photos'),
        ),
    ]
