# Generated by Django 3.1.1 on 2020-10-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201006_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='images/user_background_photos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='images/user_profile_photos'),
        ),
    ]
