# Generated by Django 3.2.4 on 2021-07-05 02:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_notification_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="notification_preferences",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (1, "Shared_Item_Likes"),
                    (2, "Messages_Received"),
                    (3, "Shared_Item_Comments"),
                    (4, "Shared_Item_Tag"),
                    (5, "Connection_Request"),
                ],
                default="1,2,3,4,5",
                max_length=9,
                null=True,
            ),
        ),
    ]
